// <auto-generated />
using System;
using Funda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Funda.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210714231518_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Funda.Data.House", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("GlobalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTuin")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Koopprijs")
                        .HasColumnType("REAL");

                    b.Property<long>("MakelaarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MakelaarNaam")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("PublicatieDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Woonplaats")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
